# Container-based Precise due to `sudo: false`
sudo: false
language: go
go:
 - 1.7
 - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - mkdir -p $HOME/gopath/src/github.com/foobarren
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/github.com/foobarren/appdash
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/foobarren/appdash
